export const SEARCH_MOVIE = 'SEARCH_MOVIE';

export const START_SEARCH = 'START_SEARCH';
export const CANCEL_SEARCH = 'CANCEL_SEARCH';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';
